name: rosse
description: A new Flutter application.

version: 0.9.1+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  path_provider: ^1.5.1
  flutter_svg: ^0.17.0
  launch_review: ^2.0.0
  path: ^1.6.4
  charts_flutter: ^0.8.1
  firebase_core: ^0.4.3+2
  firebase_database: ^3.1.3
  share: ^0.6.3+5
  intl: ^0.16.1
  flare_flutter: ^2.0.1
  after_layout: ^1.0.7+2
  file_picker: ^1.4.3+2
  percent_indicator: ^2.1.1+1
  responsive_builder: ^0.1.4
  http: ^0.12.0+4
  google_sign_in: ^4.1.1
  soundpool: ^0.6.1
  youtube_player_flutter: ^6.1.0+4
  purchases_flutter: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts: 
    - family:  IconPack
      fonts:
       - asset: fonts/IconPack.ttf
    - family:  Montserrat
      fonts:
       - asset: fonts/Montserrat-Regular.ttf
       - asset: fonts/Montserrat-ThinItalic.ttf
         weight: 100
         style: italic
       - asset: fonts/Montserrat-Thin.ttf
         weight: 100
       - asset: fonts/Montserrat-ExtraLight.ttf
         weight: 200
       - asset: fonts/Montserrat-ExtraLightItalic.ttf
         weight: 200
         style: italic
       - asset: fonts/Montserrat-Light.ttf
         weight: 300
       - asset: fonts/Montserrat-LightItalic.ttf
         weight: 300
         style: italic
       - asset: fonts/Montserrat-Medium.ttf
         weight: 500
       - asset: fonts/Montserrat-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: fonts/Montserrat-SemiBold.ttf
         weight: 600
       - asset: fonts/Montserrat-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: fonts/Montserrat-Bold.ttf
         weight: 700
       - asset: fonts/Montserrat-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: fonts/Montserrat-ExtraBold.ttf
         weight: 800
       - asset: fonts/Montserrat-ExtraBoldItalic.ttf
         weight: 800
         style: italic
       - asset: fonts/Montserrat-Black.ttf
         weight: 900
       - asset: fonts/Montserrat-BlackItalic.ttf
         weight: 900
         style: italic
       - asset: fonts/Montserrat-Italic.ttf
         style: italic
  assets:
    - assets/animations/checkbox.flr
    - assets/animations/empty_animation.flr
    - assets/g_icon.png
    - assets/svgs/stains/action_stain1.svg
    - assets/svgs/stains/action_stain2.svg
    - assets/svgs/stains/background_stain.svg
    - assets/svgs/welcome_page/welcome1.svg
    - assets/svgs/welcome_page/welcome2.svg
    - assets/svgs/welcome_page/welcome3.svg
    - assets/svgs/wides/habits.svg
    - assets/svgs/wides/nutrition.svg
    - assets/svgs/wides/sleep.svg
    - assets/sounds/tick.mp3
    - assets/svgs/empty_view.svg